export {default as Logo} from './logo.png'
export {default as Background} from './background.jpg'
export {default as google} from './google.png'
export { default as houseImage } from './headerHouse.png'
export { default as profileImage } from './profilePic.png'